forge 'forge.puppetlabs.com'
mod 'puppetlabs/ntp'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppet-collectd', '5.3.0'
mod 'sidorenko-sshkeys'
mod 'pdxcat-nrpe', '2.1.1'
mod 'saz-resolv_conf', '3.1.0'
mod 'saz-sudo', '4.1.0'
mod 'ptomulik-vash', '0.2.0'
mod 'ptomulik-portsutil', '0.1.3'
mod 'ptomulik-backports', '0.0.2'
mod 'ptomulik-portsng', '1.0.1'
mod 'yo61-logrotate', '1.4.0'
