forge 'forge.puppetlabs.com'
mod 'puppetlabs/ntp'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppet-collectd', '5.3.0'
mod 'sidorenko-sshkeys'
mod 'ptomulik-backports', '0.0.1'
mod 'ptomulik-portsng', '1.0.1'
