forge 'forge.puppetlabs.com'
mod 'puppetlabs/ntp'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppet-collectd', '5.3.0'
mod 'sidorenko-sshkeys'
mod 'zleslie-sudo', '0.3.0'
#mod 'zleslie/pkgng'
#mod 'ptomulik-vash'
#mod 'ptomulik-portsutil'
#mod 'ptomulik-backports'
#mod 'ptomulik-portsng'
